# Fly.io deployment configuration for PhantomPay
# Deploy with: fly deploy

app = "phantompay"
primary_region = "iad"  # Change to your preferred region (iad=US East, lhr=London, syd=Sydney)

[build]
  # Use Dockerfile if you create one, or use buildpacks
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "3001"
  NODE_ENV = "production"

# Persistent volume for SQLite database
[mounts]
  source = "phantompay_data"
  destination = "/data"
  initial_size = "1GB"

# HTTP service configuration
[[services]]
  internal_port = 3001
  protocol = "tcp"
  auto_stop_machines = false  # Keep machines running (important for in-memory game state)
  auto_start_machines = true
  min_machines_running = 1     # Always keep at least 1 instance running

  # HTTP ports
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true  # Redirect HTTP to HTTPS

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health check
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"

# VM resources
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512  # Increase to 1024 for better performance

